In [6]:
#pip install nltk

In [7]:
import nltk
import pandas as pd

In [8]:
#nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\nsubh\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [9]:
fake=pd.read_csv("Fake.csv")
genuine = pd.read_csv("real.csv")

In [10]:
genuine

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"
...,...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017"
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017"
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017"
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017"
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017"

In [11]:
fake['genuiness']=0
genuine['genuiness']=1

In [12]:
genuine

,title,text,subject,date,genuiness
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1
...,...,...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",1
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",1
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",1
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",1
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",1

In [13]:
dataset=pd.concat([fake,genuine])

In [14]:
dataset

,title,text,subject,date,genuiness
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0
...,...,...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",1
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",1
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",1
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",1
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",1

## Pre Processing

In [15]:
dataset = dataset.reset_index(drop=True)

In [16]:
dataset

,title,text,subject,date,genuiness
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0
...,...,...,...,...,...
44893,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",1
44894,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",1
44895,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",1
44896,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",1
44897,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",1

In [17]:
dataset = dataset.drop(['date','title','subject'],axis=1)

In [18]:
dataset

                                                    text  genuiness
0      Donald Trump just couldn t wish all Americans ...          0
1      House Intelligence Committee Chairman Devin Nu...          0
2      On Friday, it was revealed that former Milwauk...          0
3      On Christmas day, Donald Trump announced that ...          0
4      Pope Francis used his annual Christmas Day mes...          0
...                                                  ...        ...
44893  BRUSSELS (Reuters) - NATO allies on Tuesday we...          1
44894  LONDON (Reuters) - LexisNexis, a provider of l...          1
44895  MINSK (Reuters) - In the shadow of disused Sov...          1
44896  MOSCOW (Reuters) - Vatican Secretary of State ...          1
44897  JAKARTA (Reuters) - Indonesia will buy 11 Sukh...          1

[44898 rows x 2 columns]

In [19]:
from nltk.tokenize import word_tokenize
dataset['text'] = dataset['text'].apply(word_tokenize)

In [20]:
dataset

                                                    text  genuiness
0      [Donald, Trump, just, couldn, t, wish, all, Am...          0
1      [House, Intelligence, Committee, Chairman, Dev...          0
2      [On, Friday, ,, it, was, revealed, that, forme...          0
3      [On, Christmas, day, ,, Donald, Trump, announc...          0
4      [Pope, Francis, used, his, annual, Christmas, ...          0
...                                                  ...        ...
44893  [BRUSSELS, (, Reuters, ), -, NATO, allies, on,...          1
44894  [LONDON, (, Reuters, ), -, LexisNexis, ,, a, p...          1
44895  [MINSK, (, Reuters, ), -, In, the, shadow, of,...          1
44896  [MOSCOW, (, Reuters, ), -, Vatican, Secretary,...          1
44897  [JAKARTA, (, Reuters, ), -, Indonesia, will, b...          1

[44898 rows x 2 columns]

In [21]:
from nltk.stem.snowball import SnowballStemmer

In [22]:
sb = SnowballStemmer('english')

In [23]:
def stem_it(text):
    return [sb.stem(word) for word in text]

In [24]:
dataset['text'] = dataset['text'].apply(stem_it)

In [25]:
dataset

                                                    text  genuiness
0      [donald, trump, just, couldn, t, wish, all, am...          0
1      [hous, intellig, committe, chairman, devin, nu...          0
2      [on, friday, ,, it, was, reveal, that, former,...          0
3      [on, christma, day, ,, donald, trump, announc,...          0
4      [pope, franci, use, his, annual, christma, day...          0
...                                                  ...        ...
44893  [brussel, (, reuter, ), -, nato, alli, on, tue...          1
44894  [london, (, reuter, ), -, lexisnexi, ,, a, pro...          1
44895  [minsk, (, reuter, ), -, in, the, shadow, of, ...          1
44896  [moscow, (, reuter, ), -, vatican, secretari, ...          1
44897  [jakarta, (, reuter, ), -, indonesia, will, bu...          1

[44898 rows x 2 columns]

In [26]:
def stopword_revomal(text):
    return [word for word in text if len(word)>>2]

In [27]:
dataset['text'] = dataset['text'].apply(stopword_revomal)

In [28]:
dataset

                                                    text  genuiness
0      [donald, trump, just, couldn, wish, american, ...          0
1      [hous, intellig, committe, chairman, devin, nu...          0
2      [friday, reveal, that, former, milwauke, sheri...          0
3      [christma, donald, trump, announc, that, would...          0
4      [pope, franci, annual, christma, messag, rebuk...          0
...                                                  ...        ...
44893  [brussel, reuter, nato, alli, tuesday, welcom,...          1
44894  [london, reuter, lexisnexi, provid, legal, reg...          1
44895  [minsk, reuter, shadow, disus, soviet-era, fac...          1
44896  [moscow, reuter, vatican, secretari, state, ca...          1
44897  [jakarta, reuter, indonesia, will, sukhoi, fig...          1

[44898 rows x 2 columns]

In [29]:
dataset['text'] = dataset['text'].apply(' '.join)

In [30]:
dataset

                                                    text  genuiness
0      donald trump just couldn wish american happi y...          0
1      hous intellig committe chairman devin nune hav...          0
2      friday reveal that former milwauke sheriff dav...          0
3      christma donald trump announc that would back ...          0
4      pope franci annual christma messag rebuk donal...          0
...                                                  ...        ...
44893  brussel reuter nato alli tuesday welcom presid...          1
44894  london reuter lexisnexi provid legal regulator...          1
44895  minsk reuter shadow disus soviet-era factori m...          1
44896  moscow reuter vatican secretari state cardin p...          1
44897  jakarta reuter indonesia will sukhoi fighter w...          1

[44898 rows x 2 columns]

In [31]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(dataset['text'],dataset['genuiness'],test_size=0.25)

In [32]:
x_train

41176    phnom penh reuter cambodia thursday deport chi...
22383    21st centuri wire import particular worri abou...
1704     late 20th centuri author attorney mike godwin ...
18017    contrari what media would like believ obama re...
37803    tokyo reuter japanes prime minist shinzo tuesd...
                               ...
633      sure attorney general jeff session will this a...
26222    washington reuter some provis trans-pacif part...
19081    cosmet brand lush popular among young girl hip...
30745    washington reuter republican repres price geor...
15836    hate these peopl they just angri connor owner ...
Name: text, Length: 33673, dtype: object

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidfv = TfidfVectorizer(max_df = 0.7)

In [34]:
tfidfv_train = tfidfv.fit_transform(x_train)
tfidfv_test = tfidfv.transform(x_test)

In [35]:
print(tfidfv_train)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 5328353 stored elements and shape (33673, 90633)>
  Coords	Values
  (0, 62746)	0.18842191841169512
  (0, 62152)	0.18787828408947344
  (0, 68616)	0.021376800049271887
  (0, 17534)	0.3515739409816405
  (0, 80481)	0.03514135505639556
  (0, 24924)	0.18243586976044515
  (0, 19490)	0.16780081152783685
  (0, 56489)	0.025843867437227885
  (0, 86511)	0.028496154536863605
  (0, 19481)	0.23658927947867348
  (0, 78052)	0.06995076951585101
  (0, 30172)	0.08167534662208664
  (0, 54691)	0.04109746780752837
  (0, 32984)	0.034702031481238016
  (0, 62205)	0.04580634734637634
  (0, 80123)	0.04863819765731323
  (0, 60543)	0.024175136513367897
  (0, 41656)	0.11516291341995866
  (0, 79424)	0.06458075907681325
  (0, 17535)	0.18631559401570413
  (0, 63610)	0.11661055593859061
  (0, 80294)	0.03573900020399773
  (0, 66599)	0.04148201024757679
  (0, 58698)	0.07676425086218819
  (0, 78651)	0.07492664351449699
  :	:
  (33672, 31068)	0.04374598240915608
  (33672, 71022)	0.04428152393480681
  (33672, 23425)	0.04120230482233386
  (33672, 25103)	0.04246151159014768
  (33672, 63161)	0.4271433647633171
  (33672, 21524)	0.10355971180301361
  (33672, 51611)	0.04727883295026643
  (33672, 84190)	0.055514098209457984
  (33672, 6756)	0.0413373217290967
  (33672, 78047)	0.055514098209457984
  (33672, 31626)	0.04874530232407859
  (33672, 19233)	0.045122997156391086
  (33672, 32033)	0.05262994477097536
  (33672, 22914)	0.11261467973664922
  (33672, 61431)	0.05103632573085266
  (33672, 88003)	0.05963173083905376
  (33672, 77370)	0.05963173083905376
  (33672, 63166)	0.06134070278859017
  (33672, 6346)	0.06134070278859017
  (33672, 12858)	0.06134070278859017
  (33672, 86412)	0.12268140557718034
  (33672, 7096)	0.06134070278859017
  (33672, 81247)	0.06134070278859017
  (33672, 82643)	0.06134070278859017
  (33672, 60393)	0.06134070278859017

In [36]:
from sklearn.linear_model import LogisticRegression

In [39]:
lr = LogisticRegression(max_iter = 1000)
lr.fit(tfidfv_train,y_train)

LogisticRegression(max_iter=1000)

In [40]:
y_pred = lr.predict(tfidfv_test)
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.9879732739420936

In [37]:
from sklearn.linear_model import PassiveAggressiveClassifier

pac = PassiveAggressiveClassifier(max_iter = 100)
pac.fit(tfidfv_train,y_train)

PassiveAggressiveClassifier(max_iter=100)

In [41]:
y_pred_pac = pac.predict(tfidfv_test)
accuracy_score(y_test,y_pred_pac)

0.9962583518930958

In [ ]:
# Sample news text
sample_news = ["The government announced a new AI policy for schools."]

# Transform using the same TF-IDF vectorizer used in training
sample_vector = tfidfv.transform(sample_news)

# Predict using the trained model
prediction = pac.predict(sample_vector)
label_map = {0: "REAL", 1: "FAKE"}
print("Predicted Label:", label_map[prediction[0]])

Predicted Label: FAKE

In [ ]:
def test_news(text):
    vector = tfidfv.transform([text])  # Wrap text in a list
    prediction = pac.predict(vector)
    label_map = {0: "REAL", 1: "FAKE"}
    return f"Predicted Label: {label_map[prediction[0]]}"

In [ ]:
sample1 = "MOSCOW (Reuters) - Vatican Secretary of State."
sample2 = "The government announced a new AI policy for schools."

print("sample1: ",test_news(sample1))
print("sample2: ",test_news(sample2))

sample1:  Predicted Label: FAKE
sample2:  Predicted Label: REAL